title: mold # name of the site
author: Shantanu Mishra # name of site's author
email: dev@8hantanu.net # email of site's author
url: https://yree.io # root address of the site
baseurl: "/mold" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A minimal, optimized, lightweight design for static sites.

footer_content: > #footer of the site
  ##### Â© 2024 [Yree](https://yree.io) | [Github](https://github.com/yree) | [Comment](javascript:window.location='mailto:hey@yree.io?subject='+encodeURIComponent(document.title))

permalink: /:slug

favicon: "favicon.svg" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: mold # if you are using GitHub Pages, change it to remote_theme: yree/mold
remote_theme: yree/mold

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

